on:
  push:
    branches: [ "main" ]
    
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.15.0'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build:prod
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/app'
    api_location: ''
    output_location: '$(System.DefaultWorkingDirectory)/dist'
    app_artifact_location: '$(System.DefaultWorkingDirectory)/dist'
    sku: 'Free'
    # Specify the name of the Azure Static Website you created
    name: 'austinwasinger'
    # Specify the resource group that the Azure Static Website belongs to
    resourceGroupName: 'global_resource_group'
    # Specify the deployment token for the Azure Static Website
    # You can create a deployment token by following the instructions in the Azure portal:
    # https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization?tabs=cli#cli
    # Make sure to store the token securely as a secret variable in your build pipeline
    # and reference it using the $(deploymentToken) syntax
    accessToken: '$(DEPLOYMENT_TOKEN)'
  displayName: 'Deploy to Azure Static Web App'
