name: Build and deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main

env:
  AZURE_STATIC_WEB_APPS_API_LOCATION: ''

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14.x'

      # - name: Install packages
      #   run: npm install

      # - name: Build app
      #   run: npm run build -- --prod

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          # Replace with the name of the Azure Static Web App you created
          app-name: austinwasinger
          # Replace with the name of the GitHub repository that contains your app
          github-repo: sladewasinger/austinwasingerdotcom
          # Replace with the name of the branch you want to deploy
          # This should be the same branch specified in the `on` section at the top
          # of this YAML file
          branch: main
          # Replace with the path to the build output directory relative to the root of your repo
          # This should be the same directory that you specified as the output location
          # in the `angular.json` file when you ran the `ng build` command
          app-artifact-location: dist
          # Replace with the name of the Azure Static Web Apps resource group
          resource-group: global_resource_group
          # Replace with the Azure region where you want to deploy your app
          region: Central US
          # Replace with the deployment token for your Azure Static Web App
          # You can create a deployment token by following the instructions in the Azure portal:
          # https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization?tabs=cli#cli
          # Make sure to store the token securely as a secret in your GitHub repository
          # and reference it using the ${{ secrets.DEPLOYMENT_TOKEN }} syntax
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
